m4_navigation_morph:
  ros__parameters:
    use_sim_time: false
    morph_duration: 5.0
    morph_angular_velocity: 0.3

m4_navigation_tracker:
  ros__parameters:
    use_sim_time: false
    lookahead_distance: 5.0
    max_linear_velocity: 1.0
    max_angular_velocity: 1.0
    position_tolerance: 0.2
    orientation_tolerance: 0.13
    robot_frame: fcu

m4_costmap:
  ros__parameters:
    use_sim_time: false
    # General parameters
    global_frame: "Drone1/gps_origin"
    robot_base_frame: "Drone1/fcu"
    update_frequency: 30.0
    transform_tolerance: 0.5
    # Map size (in meters, centered on robot)
    width: 50.0    # 5 meters to each side
    height: 50.0   # 5 meters front and back
    resolution: 0.1  # 5cm per cell

    # Enable/disable features
    use_height_filter: true
    use_footprint_filter: false
    use_obstacle_layer: true
    use_inflation_layer: true

    # Height filter params
    min_height: 0.1
    max_height: 2.0

    # Footprint params
    footprint_radius: 0.5
    is_circular_robot: true

    # Obstacle layer params
    obstacle_range: 30.0
    raytrace_range: 3.0

    # Inflation layer params
    inflation_radius: 0.55
    cost_scaling_factor: 10.0
    pointcloud_topic: "lidar/point_cloud"

    use_invert_filter: true
    invert_x: false
    invert_y: false   # This will flip the Y coordinates
    invert_z: false