m4_navigation_morph:
  ros__parameters:
    use_sim_time: false
    morph_duration: 5.0
    morph_angular_velocity: 0.3

m4_navigation_tracker:
  ros__parameters:
    use_sim_time: false
    lookahead_distance: 2.0
    max_linear_velocity: 0.5
    max_angular_velocity: 1.0
    min_lookahead_distance: 1.0
    max_lookahead_distance: 3.0
    position_tolerance: 0.2
    orientation_tolerance: 0.13
    robot_frame: fcu